server:
  port: 30020

spring:
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    stream:
      default-binder: rabbit
  rabbitmq:
    host: 172.60.1.12
    port: 5672
    username: root
    password: 1q2w3e4r

#    spring.cloud.stream.bindings.input.binder=kafka
#    spring.cloud.stream.bindings.output.binder=rabbit

logging:
  level:
    org.springframework.cloud.consul: DEBUG

management:
  security:
    enabled: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true