server:
  port: 30020

logging:
  level:
    org.springframework.cloud.consul: DEBUG

management:
  security:
    enabled: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

spring:
  rabbitmq:
    host: maeda
    username: root
    password: 1q2w3e4r